### ISSUE TITLE
SSLError: [SSL: WRONG_VERSION_NUMBER]

### ISSUE THREAD

**Issue by rrbailey89** [RocketMap/RocketMap#1072]
With the change in server software I beleive this is the cause of the error below.
## Expected Behavior

Not to receive this error in the server window.
## Current Behavior

Current behavior is receiving this error. Im not exactly sure what causes it either.

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 126, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 691, in wrap_socket
    ciphers=ciphers)
  File "C:\Python27\lib\site-packages\gevent\_sslgte279.py", line 271, in __init__
    raise x
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
<Greenlet at 0x41e35d0: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x4209950 fileno=[Errno 9] Bad file de)> failed with SSLError
```
## Steps to Reproduce (for bugs)

1. Be on latest git pull
2. Run in ssl
3. Observe logs for awhile.
   4.
## Context

It does not really seem to effect anything at all. I am still able to browse the site and the SSL cert seems to still get passed and be valid.
## Your Environment

- Version used: Latest git pull.
- Environment name and version (e.g. Python 2.7): 2.7
- Operating System and version (desktop or mobile): Windows 10

**Comment by NGPriest** [comment]
Having same problem, would love to see a resolution...

**Comment by SM411** [comment]
I also get this error.

**Comment by NGPriest** [comment]
It appears that people are trying to access your site via http instead of https...

**Comment by bootsmann** [comment]
with https:
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 25, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 126, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 691, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 271, in __init__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:581)
<Greenlet at 0x751e8300: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x751ec610 fileno=[Errno 9] Bad file d)> failed with SSLError`

**Comment by sebastienvercammen** [comment]
Issue is no longer related to the current codebase, so we're closing the issue. If anyone still has the problem, please post additional data on latest commit and we'll reopen.
