### ISSUE TITLE
Create Tables paradox

### ISSUE THREAD

**Issue by Xcelled** [RocketMap/RocketMap#1106]
## Expected Behavior

Migration should happen automatically
## Current Behavior

When migrating, the program checks the DB schema version and upgrades it first. If the migration relies on a new table, that table is not created before the migration runs, resulting in a missing table error.
## Possible Solution

Reorder table creation to appear before the schema upgrade, or possibly integrate table creation into the migration code.
## Steps to Reproduce (for bugs)

1. Run a pogom on db schema version 5
2. Update the code to version 7
3. Run the program
## Context

Couldn't run the program without manually reordering the create calls.

```
2016-09-02 18:08:58,022 [      MainThread][     runserver][    INFO] Parsed location is: 43.0833/-77.6784/163.4727 (lat/lng/alt)
2016-09-02 18:08:58,081 [      MainThread][        models][    INFO] Connecting
to MySQL database on localhost:3306
2016-09-02 18:08:58,179 [      MainThread][        models][    INFO] Detected database version 5, updating to 7
Traceback (most recent call last):
  File "runserver.py", line 250, in <module>
    main()
  File "runserver.py", line 160, in main
    create_tables(db)
  File "/home/scott/PokemonGo-Map/pogom/models.py", line 851, in create_tables
    verify_database_schema(db)
  File "/home/scott/PokemonGo-Map/pogom/models.py", line 879, in verify_database_schema
    database_migrate(db, db_ver)
  File "/home/scott/PokemonGo-Map/pogom/models.py", line 935, in database_migrate
    migrator.add_column('gymdetails', 'description', TextField(null=True, default=""))
  File "/usr/local/lib/python2.7/dist-packages/playhouse/migrate.py", line 684,
in migrate
    operation.run()
  File "/usr/local/lib/python2.7/dist-packages/playhouse/migrate.py", line 144,
in run
    getattr(self.migrator, self.method)(*self.args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/playhouse/migrate.py", line 133,
in _handle_result
    self.execute(result)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/migrate.py", line 129,
in execute
    self.migrator.database.execute_sql(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 161, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 317, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1021, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
peewee.ProgrammingError: (1146, u"Table 'pogom.gymdetails' doesn't exist")
```
## Your Environment

- Version used: develop
- Environment name and version (e.g. Python 2.7):  2.7.9
- Operating System and version (desktop or mobile): Raspbian

**Comment by pyr0ball** [comment]
+1 from me on this

**Comment by Wolfsblvt** [comment]
Same error here.
Also note that if the migration throws an exception (like this one here) the execution breaks, but version number in DB is already set to 7. So the migration is not rolled back or anything, and I am quite sure it hasn't finished everything.

**Comment by averylarry** [comment]
Anyone have a way to fix this?  Xcelled mentioned manually reordering the create calls . . ?

**Comment by Xcelled** [comment]
If you have already run the migration (ie are on db version 7+), you need to reset the version number in your database to what it was prior to the attempted upgrade. In my case, this was 5, and I used an sql browser.

Once you've re-lowered your version, comment this line and run the program: https://github.com/PokemonGoMap/PokemonGo-Map/blob/d5d6d10c92103cd0535d71cb06b73c66c1de361d/pogom/models.py#L901

Once scanning starts, close the program, uncomment the line, and it should then migrate without issue.

Possibly swapping the highlighted line with the one below it would be sufficient. but I haven't tested this.

**Comment by azd2** [comment]
I solved it by deleting the whole DB, recreate an empty one and start the server. Empty DB of course, but at least it worked again and i didn't care about old entries.

**Comment by averylarry** [comment]
I flipped those 2 lines and it seems to be working.  Not that it really didn't work before since I don't scan gyms, but I don't have the error messages.  So far, at least.  I don't think the lines should be left reversed, though.  The schema upgrade/migration code was a little complicated for me to follow without spending more time than I'd like, so I'll let those who know it better figure out how to permanently fix it.

**Comment by Xcelled** [comment]
I think the proper thing to do is overhaul the migration code. Way back in #589 I made some important changes to migration to reduce a number of issues. I could revive them and move the table creation into migrations.

**Comment by prusswan** [comment]
yeah upgrading from 4 to 7 and ran into this

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
