### ISSUE TITLE
gym-info database issues with non-localhost MySQL

### ISSUE THREAD

**Issue by badboiaustria** [RocketMap/RocketMap#1163]
## Expected Behavior

Run with config gym-info:true  on MySQL Db hosted on remote server should run without issues
## Current Behavior

Run with config gym-info:true  on MySQL Db hosted on remote server sometimes (always after 10 seconds, after getting login tokens) gives error: "Cant connect to MySQL server.."
Turning gym-info off results in correct handling of MySQL DB (although it also occurs in rare occasions)
## Possible Solution

I assume the gym-info module was optimized for localhost DB servers. Delayed response times from remote MySQL server results in errors. We are talking about 400-700ms here.
## Steps to Reproduce (for bugs)

1. set gym-info: true
2. set MySQL DB server to a remote server
## Context

gym-info: true is not usable with remote MySQL server
## Your Environment

- Version used: latest development
- Environment name and version (e.g. Python 2.7): python 2.7
- Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by azd2** [comment]
Please check your Network and/or SQL-Server... 
Running the exact same configuration. 
MySQL Server on FreeBSD 10 (Jail in Nas4free), 
"Always-on" Server+ some scanner instances on VmWare ESXI Windows VMs and 
some other not always on scanner instances on gaming PC. 
So alltogether 3 different **physical** hosts, counting VMs it's 5 different hosts. Roundabout 300 Accounts active, MySQL shows 327 connections. 
Absolutely no problems at all with gym-info:true
This ran "out of the box", only change: had to raise mysql max connections from 150.

How do you get 400-700 ms response time? Scanner in US, SQL Server in Europe?

**Comment by badboiaustria** [comment]
Hi!
thanks for the answer. max connections is on 800, I am only using 8 accounts. round trip delay is obviously max. 100ms.

Initial start works fine:
2016-09-07 15:15:55,072 [      MainThread][        models][    INFO] Connecting to MySQL database on e51481-mysql.servic
es.easyname.eu:3306
2016-09-07 15:15:55,792 [ search-overseer][        search][    INFO] Search overseer starting
2016-09-07 15:15:55,798 [ search-overseer][        search][    INFO] Starting account recycler thread
2016-09-07 15:15:55,802 [ search-overseer][        search][    INFO] Starting search worker threads
2016-09-07 15:15:55,808 [ search-worker-0][        search][    INFO] Waiting to get new account from the queue
2016-09-07 15:15:55,809 [ search-worker-1][        search][    INFO] Waiting to get new account from the queue

but then (only with gym-info:true)

2016-09-07 15:16:06,835 [search-worker-10][      auth_ptc][    INFO] PTC User Login successful.
2016-09-07 15:16:06,839 [search-worker-10][      auth_ptc][    INFO] Request PTC Access Token...
2016-09-07 15:16:07,042 [search-worker-10][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-09-07 15:16:17,921 [ search-worker-0][        models][    INFO] Parsing found 2 pokemons, 183 pokestops, and 15 gym
s
2016-09-07 15:16:19,178 [ search-worker-1][        models][    INFO] Parsing found 2 pokemons, 183 pokestops, and 15 gym
s
2016-09-07 15:16:20,084 [ search-worker-2][        models][    INFO] Parsing found 2 pokemons, 183 pokestops, and 15 gym
s
2016-09-07 15:16:20,757 [ search-worker-3][        models][    INFO] Parsing found 2 pokemons, 183 pokestops, and 15 gym
s
[2016-09-07 15:16:21,279] ERROR in app: Exception on /raw_data [GET]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python 2\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files (x86)\Python 2\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files (x86)\Python 2\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files (x86)\Python 2\lib\site-packages\flask\app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Program Files (x86)\Python 2\lib\site-packages\flask\app.py", line 1837, in preprocess_request
    rv = func()
  File "C:\Program Files (x86)\Python 2\lib\site-packages\playhouse\flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "C:\Program Files (x86)\Python 2\lib\site-packages\peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)
  File "C:\Program Files (x86)\Python 2\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Program Files (x86)\Python 2\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "C:\Program Files (x86)\Python 2\lib\site-packages\playhouse\pool.py", line 128, in _connect
    conn = super(PooledDatabase, self)._connect(*args, **kwargs)
  File "C:\Program Files (x86)\Python 2\lib\site-packages\peewee.py", line 3929, in _connect
    return mysql.connect(db=database, **conn_kwargs)
  File "C:\Program Files (x86)\Python 2\lib\site-packages\pymysql\__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "C:\Program Files (x86)\Python 2\lib\site-packages\pymysql\connections.py", line 690, in __init__
    self.connect()
  File "C:\Program Files (x86)\Python 2\lib\site-packages\pymysql\connections.py", line 939, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on 'e51481-mysql.services.easyname.eu' ([Errno 10061] Es konnte
keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte)")

**Comment by badboiaustria** [comment]
this is how it looks with gym-info disabled. everything alright:
2016-09-07 15:24:48,311 [ search-worker-6][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:24:48,545 [ search-worker-6][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:24:49,308 [ search-worker-7][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:24:49,559 [ search-worker-7][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:24:50,308 [ search-worker-8][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:24:50,849 [ search-worker-8][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:24:51,359 [ search-worker-9][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:24:51,591 [ search-worker-9][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:24:52,309 [search-worker-10][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:24:52,535 [search-worker-10][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:00,230 [account-recycler][        search][    INFO] Account recycler running. Checking status of 0 accounts
2016-09-07 15:25:00,815 [      db-cleaner][        models][    INFO] Regular database cleaning complete
2016-09-07 15:25:02,625 [ search-worker-0][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:02,973 [ search-worker-0][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:03,849 [ search-worker-1][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:04,092 [ search-worker-1][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:04,546 [ search-worker-2][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:04,792 [ search-worker-2][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:05,602 [ search-worker-3][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:05,822 [ search-worker-3][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:06,961 [ search-worker-4][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:07,210 [ search-worker-4][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:07,615 [ search-worker-5][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:07,888 [ search-worker-5][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:08,548 [ search-worker-6][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:08,819 [ search-worker-6][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:09,565 [ search-worker-7][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:09,803 [ search-worker-7][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:10,852 [ search-worker-8][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:11,081 [ search-worker-8][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:11,595 [ search-worker-9][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:11,841 [ search-worker-9][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:12,538 [search-worker-10][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:12,795 [search-worker-10][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:22,982 [ search-worker-0][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:23,223 [ search-worker-0][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:24,095 [ search-worker-1][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:24,332 [ search-worker-1][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:24,796 [ search-worker-2][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:25,036 [ search-worker-2][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:25,825 [ search-worker-3][        search][    INFO] Searching at 48.082550,16.286900
2016-09-07 15:25:26,059 [ search-worker-3][        models][    INFO] Parsing found 1 pokemons, 183 pokestops, and 15 gyms
2016-09-07 15:25:27,213 [ search-worker-4][        search][    INFO] Searching at 48.082550,16.286900

**Comment by azd2** [comment]
So what exactly is your setup?
Your sql db is hosted at easyname.at. Where are your scanners located? 
Did you ever try it with fewer workers (1-4)?

**Comment by badboiaustria** [comment]
even with one worker it happens. actually without opening the webpage there is no problem, but as soon as I do the reload on the webfrontend the DB errors occur. and as soon as the pointer is moved.

I just realized it also happens with gym-info disabled - on reload of the webpage. but with gym-info enabled it happens much more often. strange.

**Comment by azd2** [comment]
Switching Gym info on:  many Read/write request to sql db
Reloading map: many reqs to db at once
relocating pointer: many reqs at once

This sounds like your hoster is somehow limiting the requests to the sql db you may do. 
I strongly believe this is not an issue with "non-localhost db", but with sql db hosted at your provider...
I don't know where your workers are doing their work, machine at home or at provider too, but if youre running only 8 accs, the integrated database is more than sufficient. I'd take that route...

**Comment by badboiaustria** [comment]
I think you are correct.

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
