### ISSUE TITLE
Errors With Script While Using Proxy

### ISSUE THREAD

**Issue by RogueMaster** [RocketMap/RocketMap#1210]
## Expected Behavior

No errors...
## Current Behavior

This is my only running worker at the moment. Testing proxy setup.

```

2016-09-08 01:58:04,983 [      MainThread][        models][    INFO] Connecting to MySQL database on 127.0.0.1:3306
2016-09-08 01:58:04,993 [      MainThread][         proxy][    INFO] Checking 1 proxies...
2016-09-08 01:58:05,033 [      db-cleaner][        models][    INFO] Regular database cleaning complete
2016-09-08 01:58:06,687 [      MainThread][         proxy][    INFO] Proxy check completed with 1 working proxies of 1 configured
2016-09-08 01:58:06,688 [ search-overseer][        search][    INFO] Search overseer starting
2016-09-08 01:58:06,694 [ search-overseer][        search][    INFO] Starting account recycler thread
2016-09-08 01:58:06,698 [ search-overseer][        search][    INFO] Starting status database thread
2016-09-08 01:58:06,698 [ search-overseer][        search][    INFO] Starting search worker threads
...
2016-09-08 01:59:17,960 [       Thread-44][           app][   ERROR] Exception on /raw_data [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1837, in preprocess_request
    rv = func()
  File "C:\Python27\lib\site-packages\playhouse\flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "C:\Python27\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "C:\Python27\lib\site-packages\playhouse\pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.
```
## Possible Solution

Unknown. I have attempted updating everything to no avail.
## Steps to Reproduce (for bugs)

1. Using mysql DB on windows
2. Configure with socks5 proxy
## Context

These errors constantly come up. Not sure if it is affecting scans.
## Your Environment

- Version used: Latest develop build (2016-09-08 2:00AM)
- Environment name and version (e.g. Python 2.7): Python 2.7
- Operating System and version (desktop or mobile): Windows 10

**Comment by pbrent84** [comment]
This is not a proxy issue I am having it as well without proxy.
It started when I started using SSL got more frequent when we reverted back to Flask. 
My current work around was to separate instances with -ns -os and have -os restart every 10 mins 
(not ideal but let me know how to correctly fix)

**Comment by RogueMaster** [comment]
I went into the C:\Python27\lib\site-packages\playhouse\pool.py file and changed the max_connections from 20 to 920 on line 73. Seems to have "fixed" the issue.

**Comment by pbrent84** [comment]
thanks it looks like its holding up for now

**Comment by angrymoose** [comment]
the flag for max connections is --db-max_connections 920

**Comment by slideup-benni** [comment]
@angrymoose do you really think this fixes the problem?

I have the same issue, i will test your solution but "Exceeded maximum connections." will also thrown when the server requests css-files or images. They have nothing to do with a database-limitation

**Comment by sngreco** [comment]
Same error, modifying to 920 made no difference for me.  I notice that I just have to refresh the page to reproduce the issue.

**Comment by toshioson** [comment]
Having the same problem without using proxy on my -os instance.
Error message as shown below,

```
[2016-09-26 13:44:49,828] ERROR in app: Exception on /static/b3248cc/js/vendor/modernizr.custom.js [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1837, in preprocess_request
    rv = func()
  File "C:\Python27\lib\site-packages\playhouse\flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "C:\Python27\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "C:\Python27\lib\site-packages\playhouse\pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.
```

**Comment by NHellFire** [comment]
Not a proxy issue, there's a bug somewhere.
I'm getting this too, with my max connections set to 10000. mysql process list shows it only has ~50 open, but for some reason playhouse thinks there's thousands.

Added a little debug info to playhouse:
```
In Use: 10000
Max Connections: 10000
[2017-03-09 00:32:30,072] ERROR in app: Exception on /status [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1837, in preprocess_request
    rv = func()
  File "/usr/local/lib/python2.7/dist-packages/playhouse/flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/pool.py", line 128, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.
```

It looks like after connections are finished with, they're not being returned to the pool. Not sure if this is a bug in playhouse or how playhouse is being used.

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
