### ISSUE TITLE
Zero divison Error

### ISSUE THREAD

**Issue by drallieiv** [RocketMap/RocketMap#1731]
From time to time I ham getting the folowing stack : 

```
[ search-worker-2][        search][   ERROR] Map parse failed at ***/***, abandoning location. <account> may be banned.. Exception message: float division by zero
Traceback (most recent call last):
  File "/root/PokemonGo-Map/versions/latest/pogom/search.py", line 859, in search_worker_thread
    args, response_dict, step_location, dbq, whq, api, scan_date, scheduler)
  File "/root/PokemonGo-Map/versions/latest/pogom/models.py", line 1552, in parse_map
    tth_found = tth_found * 100.0 / getattr(scheduler, 'active_sp', 100.0)
ZeroDivisionError: float division by zero
```

## Expected Behavior
Either active_sp should not be able to be 0 or it should be checked

## Current Behavior
getattr returns 0 and division failes

## Context
local map 

## Your Environment
* Version used: latest develop fdb4412
* Unix debian

**Comment by sebastienvercammen** [comment]
This problem was fixed in b8171d72754c31194749ac3cc0a72c7dd4678393, 6 days ago.
