### ISSUE TITLE
Error 32 Broken Pipe

### ISSUE THREAD

**Issue by Demokdawa** [RocketMap/RocketMap#1765]
When a user close page when data is send to it, i get this error in the webserver logs.
With few users, i get spam by this :p
## Current Behavior
That's the issue :

Exception in thread Thread-64:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

## Steps to Reproduce (for bugs)
1.Start server
2.Check console for data to be requested
3.Close the window or abort the request
4.Check terminal

## Context
Every broken pipe error i get on my server slow it ! So after few hours of broken pipe errors, my scanner processes just stop working, 'cause of the lag :/

## Your Environment
Python 2.7
Ubuntu 14

**Comment by tobias86aa** [comment]
Traceback (most recent call last):
  File "runserver.py", line 102, in run
    run_old(args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(self.args, **self.kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in init
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

I end up whit this error to

I use 
Python 2.7.12 and Ubuntu 16

Should be nice to see a fix for this.

**Comment by elincognito** [comment]
This also happens to me although I never noticed the instance slowing down, maybe because I'm constantly restarting to update :)

**Comment by FrostTheFox** [comment]
Known issue, due to flask, for the moment we can't fix this without moving to gevent/unicorn, etc

**Comment by FrostTheFox** [comment]
closing for now

**Comment by kirkisanon** [comment]
What do you recommend doing for a temp fix?
