### ISSUE TITLE
Connecting to a domain database

### ISSUE THREAD

**Issue by Clamb94** [RocketMap/RocketMap#1788]
I'm trying to connect RocketMap to a mySQL database hosted by Strato, but I don't have a IP adress, only a domain name.  I'm using the information given to me by Strato. My config.ini looks like this:

db-type: mysql
db-host: rdbms.strato.de
db-name: DB285xxxx
db-user: U285xxxx
db-pass: passwordxxx

I tried services to trace back the domain and get an IP, but this didn't work out eiter. 

## Expected Behavior
Establish a connection to a strato database.

## Current Behavior

`2017-01-31 11:14:28,016 [      MainThread][        models][    INFO] Connecting                                                                                                                                                        to MySQL database on rdbms.strato.de:3306...
2017-01-31 11:14:49,065 [      MainThread][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "runserver.py", line 356, in <module>
    main()
  File "runserver.py", line 234, in main
    create_tables(db)
  File "C:\Users\axel\Desktop\Pokemap\RocketMap\pogom\models.py", line 2221, in create_tables
    db.connect()
  File "D:\Programme\Phyton27\lib\site-packages\peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)
  File "D:\Programme\Phyton27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "D:\Programme\Phyton27\lib\site-packages\peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "D:\Programme\Phyton27\lib\site-packages\playhouse\pool.py", line 128, in _connect
    conn = super(PooledDatabase, self)._connect(*args, **kwargs)
  File "D:\Programme\Phyton27\lib\site-packages\peewee.py", line 3929, in _connect
    return mysql.connect(db=database, **conn_kwargs)
  File "D:\Programme\Phyton27\lib\site-packages\pymysql\__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "D:\Programme\Phyton27\lib\site-packages\pymysql\connections.py", line 690, in __init__
    self.connect()
  File "D:\Programme\Phyton27\lib\site-packages\pymysql\connections.py", line 939, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on 'rdbms.strato.de' ([Errno 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimm                                                           ten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat)")
`
The last part in german basically means:"Connection failed, because the other side hasn't responded after a certain time, or the connection was faulty because the connected host did not react.

If it helps I can give you the login information to my strato database (privat obviously)

### our Environment

* Version used: latest develop build
* Environment name and version: Python 2.7
* Operating System and version (desktop or mobile): Win10 64bit

Best regards

**Comment by jagauthier** [comment]
This is definitely not a rocketmap issue, and you should talk to Strato.
I did a quick google and found this from September.

http://stackoverflow.com/questions/28138413/can-not-connect-to-mysql-database-strato

**Comment by Clamb94** [comment]
Jep, what a shame. Thats why I closed it. Sorry
