### ISSUE TITLE
Got this error from fresh installation and new created account (verified)

### ISSUE THREAD

**Issue by z3cr3t** [RocketMap/RocketMap#1959]
2017-03-30 11:57:25,750 [        MainThread][           app][    INFO] Retrieving blacklist...
2017-03-30 11:57:26,102 [        MainThread][        models][    INFO] Connecting to local SQLite database
2017-03-30 11:57:26,109 [        db-cleaner][        models][    INFO] Regular database cleaning complete.
2017-03-30 11:57:26,110 [        MainThread][         proxy][    INFO] No proxies are configured.
2017-03-30 11:57:26,110 [        MainThread][     runserver][    INFO] Periodical proxies refresh disabled.
2017-03-30 11:57:26,111 [   search-overseer][        search][    INFO] Search overseer starting...
2017-03-30 11:57:26,111 [   search-overseer][        search][    INFO] Starting account recycler thread...
2017-03-30 11:57:26,111 [   search-overseer][        search][    INFO] Starting search worker threads...
2017-03-30 11:57:26,112 [   search-overseer][        search][    INFO] Enabling new API force Watchdog.
2017-03-30 11:57:26,112 [   search-overseer][        search][    INFO] New location caught, moving search grid.
2017-03-30 11:57:27,120 [   search-worker-0][        search][    INFO] Waiting to get new account from the queue...
2017-03-30 11:57:27,124 [   search-worker-0][        search][    INFO] Switching to account user.
2017-03-30 11:57:33,224 [   search-worker-0][      auth_ptc][    INFO] PTC User Login for: user
2017-03-30 11:57:35,659 [   search-worker-0][      auth_ptc][    INFO] PTC User Login successful.
2017-03-30 11:57:58,878 [   search-worker-0][        search][    INFO] Completing tutorial steps for pokemapatest.
2017-03-30 11:58:26,170 [        db-cleaner][        models][    INFO] Regular database cleaning complete.
2017-03-30 11:58:26,171 [  account-recycler][        search][    INFO] Account recycler running. Checking status of 0 accounts.
2017-03-30 11:58:41,208 [   search-worker-0][        search][    INFO] Searching at 9.663506,123.847141,14.099096.
2017-03-30 11:58:41,387 [   search-worker-0][       captcha][   ERROR] Unable to check captcha: 'CHECK_CHALLENGE'
2017-03-30 11:58:41,388 [   search-worker-0][        search][   ERROR] Map parse failed at 9.663506,123.847141, abandoning location. user may be banned.. Exception message: KeyError('GET_MAP_OBJECTS',)
Traceback (most recent call last):
  File "/root/RocketMap/pogom/search.py", line 991, in search_worker_thread
    dbq, whq, api, scan_date, account)
  File "/root/RocketMap/pogom/models.py", line 1706, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'GET_MAP_OBJECTS'

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by SwenWacker** [comment]
Please read the wiki: http://rocketmap.readthedocs.io/en/develop/extras/faq.html?highlight=map_cells

Further Support: https://discordapp.com/invite/rocketmap

**Comment by M3G4THEKING** [comment]
@SwenWacker  this is not total correct "cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']

KeyError: 'map_cells'  = The account is banned or hasn’t completed the tutorial.  before i have same problem but i have found my way to solve  . Accounts and ips are all fine.

https://github.com/RocketMap/RocketMap/issues/1926#issuecomment-287565998  

And even sometimes i still have this error and i need to use  http instead https in hash_server.py  .

**Comment by z3cr3t** [comment]
@SwenWacker yep I already read it but still no luck. Im using ubuntu 14.04 but the problem keeps repeating it self in every fresh installation.

**Comment by Plop** [comment]
Also got this error, since a few days now.

![image](https://cloud.githubusercontent.com/assets/876470/24898404/1bbf595e-1e9d-11e7-9b21-f97ea46c71b5.png)

I tried all [this ](https://github.com/RocketMap/RocketMap/issues/1926#issuecomment-287565998), and it worked for only ONE instance. The other two got the errors.

I did a full clean install, deleted the repo, git cloned again, I checked if the accounts were banned (they're not), my proxies are fine and not banned, I uninstalled the pgoapi, then updated the requirements, I'm not using any PR, i'm up-to-date, I ran the npm install...

I don't know what else I could try, and I got only one instance on three that is working. Don't really understand why.

**Comment by Clamb94** [comment]
Same problem as Plop. Some instances are working fine, other retuning tons of par_cells errors

**Comment by mimikq** [comment]
ok i have that issue today to and one guy told ask me one important think , which i did know also, it is all account done in a game by tutorial and at least lv2 an higher?  And after that and did have any issue with account, This was my solution, question is how to pass it without login to app and .....

**Comment by Plop** [comment]
I still got this problem, with a fresh and new install of RocketMap. New accounts, verified, ToS accepted, tutorial done, proxies are fine... I really don't understand why I can run one instance without any issue, and then I can't run others.

**Comment by sebastienvercammen** [comment]
Does this error still occur today after you run the following commands?
```
pip uninstall pgoapi
pip install -r requirements.txt --upgrade
```

**Comment by sebastienvercammen** [comment]
13 days without answer, closing.
