### ISSUE TITLE
Codec can't decode byte 0x9e

### ISSUE THREAD

**Issue by virtuals78** [RocketMap/RocketMap#1969]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/RocketMap/pogom/app.py", line 303, in raw_data
    timestamp=timestamp)
  File "/root/RocketMap/pogom/models.py", line 631, in get_gyms
    for d in details:
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2047, in next
    obj = self.qrw.iterate()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2107, in iterate
    return self.process_row(row)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2196, in process_row
    res[column] = func(row[i])
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 932, in python_value
    return value if value is None else self.coerce(value)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1059, in coerce
    return coerce_to_unicode(value or '')
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 1040, in coerce_to_unicode
    return s.decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9e in position 3: invalid start byte

**Comment by SiteEffect** [comment]
What coding is your DB set to? Make sure it's something like ``utf8_general_ci`` for example.
This is a read issue, no write issue. Also make sure to identify when exactly this happens and maybe which row produces it.

**Comment by sebastienvercammen** [comment]
Fixed in #2015.
