### ISSUE TITLE
HI i am new at this 

### ISSUE THREAD

**Issue by gatesjr83** [RocketMap/RocketMap#1989]
so i am new at this trying to setup following the video, after everything i and now getting this error

PS C:\Users\jador\Desktop\Rocket Map\rocketmap> python runserver.py
2017-04-28 01:26:43,210 [        MainThread][     runserver][    INFO] Parsed location is: 43.9746/-75.9097/140.0897 (lat/lng/alt)
2017-04-28 01:26:43,226 [        MainThread][           app][    INFO] Retrieving blacklist...
2017-04-28 01:26:43,927 [        MainThread][        models][    INFO] Connecting to local SQLite database
2017-04-28 01:26:43,960 [        MainThread][         proxy][    INFO] No proxies are configured.
2017-04-28 01:26:43,960 [        MainThread][     runserver][    INFO] Periodical proxies refresh disabled.
2017-04-28 01:26:43,960 [   search-overseer][        search][    INFO] Search overseer starting...
2017-04-28 01:26:43,960 [   search-overseer][        search][    INFO] Enabling hashing key scheduler...
2017-04-28 01:26:43,960 [   search-overseer][        search][    INFO] Starting account recycler thread...
2017-04-28 01:26:43,960 [   search-overseer][        search][    INFO] Starting search worker threads...
2017-04-28 01:26:43,960 [        db-cleaner][        models][    INFO] Regular database cleaning complete.
2017-04-28 01:26:43,974 [   search-overseer][        search][    INFO] Enabling new API force Watchdog.
2017-04-28 01:26:43,974 [   search-overseer][        search][    INFO] New location caught, moving search grid.
2017-04-28 01:26:44,612 [   search-overseer][    schedulers][    INFO] 397 steps created
2017-04-28 01:26:44,612 [   search-overseer][    schedulers][    INFO] Initial spawnpoint scan, 0 of 1985 bands are done or 0.0% complete
2017-04-28 01:26:44,628 [   search-overseer][    schedulers][    INFO] No spawnpoints in hex found in SpawnPoint table. Doing initial scan.
2017-04-28 01:26:44,628 [   search-overseer][    schedulers][    INFO] Found 0 spawn points within hex
2017-04-28 01:26:44,628 [   search-overseer][    schedulers][    INFO] Doing 0 distance calcs to assign spawn points to scans
2017-04-28 01:26:44,628 [   search-overseer][    schedulers][    INFO] Spawn points assigned
2017-04-28 01:26:44,628 [   search-overseer][    schedulers][    INFO] Refreshing queue
2017-04-28 01:26:44,644 [   search-overseer][        search][   ERROR] Schedule creation had an Exception: OperationalError('too many SQL variables',).
Traceback (most recent call last):
  File "C:\Users\jador\Desktop\Rocket Map\rocketmap\pogom\search.py", line 528, in search_overseer_thread
    scheduler_array[i].schedule()
  File "C:\Users\jador\Desktop\Rocket Map\rocketmap\pogom\schedulers.py", line 686, in schedule
    self.scans.keys(), self.location_change_date))
  File "C:\Users\jador\Desktop\Rocket Map\rocketmap\pogom\models.py", line 964, in get_cell_to_linked_spawn_points
    l = list(query)
  File "C:\Python27\lib\site-packages\peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "C:\Python27\lib\site-packages\peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "C:\Python27\lib\site-packages\peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\Python27\lib\site-packages\peewee.py", line 3492, in execute_sql
    self.commit()
  File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\Python27\lib\site-packages\peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: too many SQL variables

i can add config if needed thanks in advanced for the help

**Comment by walaoaaa1234** [comment]
# [Discord](https://discord.gg/rocketmap) for general support.

**Comment by gatesjr83** [comment]
thanks i am trying i went into help section not getting response, i did !sqlite got respond about maria db and installed and still the same error @walaoaaa1234

**Comment by FrostTheFox** [comment]
Not a bug, SQLite related error. Please use [Discord](http://discord.gg/RocketMap)
