### ISSUE TITLE
Crash while installing Requirements

### ISSUE THREAD

**Issue by Lord-Haji** [RocketMap/RocketMap#2014]
Log:
```
E:\>cd RocketMap

E:\RocketMap>pip install -r requirements.txt
Collecting six==1.10.0 (from -r requirements.txt (line 1))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting Flask==0.11.1 (from -r requirements.txt (line 2))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
    100% |████████████████████████████████| 81kB 149kB/s
Collecting Jinja2==2.8 (from -r requirements.txt (line 3))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 233kB/s
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 4))
  Downloading MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 5))
  Downloading Werkzeug-0.11.10-py2.py3-none-any.whl (306kB)
    100% |████████████████████████████████| 307kB 387kB/s
Collecting configargparse==0.10.0 (from -r requirements.txt (line 6))
  Downloading ConfigArgParse-0.10.0.tar.gz
Collecting click==6.6 (from -r requirements.txt (line 7))
  Downloading click-6.6-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 401kB/s
Collecting itsdangerous==0.24 (from -r requirements.txt (line 8))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 592kB/s
Collecting peewee==2.8.1 (from -r requirements.txt (line 9))
  Downloading peewee-2.8.1.tar.gz (474kB)
    100% |████████████████████████████████| 481kB 410kB/s
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 10))
  Downloading wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Haji\AppData\Local\Temp\pip-build-tbjqtp0b\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "C:\Users\Haji\AppData\Local\Temp\pip-build-tbjqtp0b\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Haji\AppData\Local\Temp\pip-build-tbjqtp0b\wsgiref\

E:\RocketMap>pip install -r requirements.txt --upgrade
Collecting six==1.10.0 (from -r requirements.txt (line 1))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting Flask==0.11.1 (from -r requirements.txt (line 2))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting Jinja2==2.8 (from -r requirements.txt (line 3))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 4))
  Using cached MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 5))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting configargparse==0.10.0 (from -r requirements.txt (line 6))
  Using cached ConfigArgParse-0.10.0.tar.gz
Collecting click==6.6 (from -r requirements.txt (line 7))
  Using cached click-6.6-py2.py3-none-any.whl
Collecting itsdangerous==0.24 (from -r requirements.txt (line 8))
  Using cached itsdangerous-0.24.tar.gz
Collecting peewee==2.8.1 (from -r requirements.txt (line 9))
  Using cached peewee-2.8.1.tar.gz
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 10))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Haji\AppData\Local\Temp\pip-build-92iaqunc\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "C:\Users\Haji\AppData\Local\Temp\pip-build-92iaqunc\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Haji\AppData\Local\Temp\pip-build-92iaqunc\wsgiref\
```

**Comment by walaoaaa1234** [comment]
@Lord-Haji python 2 or 3?
EDIT: RocketMap use **python2**

**Comment by Lord-Haji** [comment]
python 3 @walaoaaa1234

**Comment by walaoaaa1234** [comment]
@Lord-Haji use python2

**Comment by sebastienvercammen** [comment]
^ Use py2, as explained in the docs.
