### ISSUE TITLE
Error when installing to Jelastic

### ISSUE THREAD

**Issue by daalien** [RocketMap/RocketMap#2022]
I'm trying to do a "1-click" install to jelastic as they have the manifest to be able to do it. I'm guessing that at one stage it was working. I tried on the weekend was getting:

We believe, that the issue with RocketMap could be connected
to broken dependencies with Google Protocol Buffers (prtobuf)
and this issue https://github.com/google/protobuf/issues/3042
 
Here are some tracebacks from run.log:
 
Traceback (most recent call last):
  File "./runserver.py", line 20, in <module>
    from pogom.app import Pogom
  File "/usr/src/app/pogom/app.py", line 19, in <module>
    from .models import (Pokemon, Gym, Pokestop, ScannedLocation,
  File "/usr/src/app/pogom/models.py", line 36, in <module>
    from .account import (tutorial_pokestop_spin, get_player_level, check_login,
  File "/usr/src/app/pogom/account.py", line 10, in <module>
    from pgoapi import PGoApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 33, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/rpc_api.py", line 38, in <module>
    from protobuf_to_dict import protobuf_to_dict
  File "/usr/local/lib/python2.7/site-packages/protobuf_to_dict.py", line 7, in <module>
    from google.protobuf.descriptor import FieldDescriptor
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: libprotobuf.so.13: cannot open shared object file: No such file or directory
 
The developer of the maps should be contacted to resolve this issue.

**Comment by Alphawarz** [comment]
I believe it is a dockerfile issue, perhaps an update to that specific file is necessary to allow it to run as it was running before.

(Been using docker with rocketmap however this particular update recently has caused the same problem)

Traceback (most recent call last):
  File "./runserver.py", line 20, in <module>
    from pogom.app import Pogom
  File "/usr/src/app/pogom/app.py", line 19, in <module>
    from .models import (Pokemon, Gym, Pokestop, ScannedLocation,
  File "/usr/src/app/pogom/models.py", line 36, in <module>
    from .account import (tutorial_pokestop_spin, get_player_level, check_login,
  File "/usr/src/app/pogom/account.py", line 10, in <module>
    from pgoapi import PGoApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 33, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/rpc_api.py", line 38, in <module>
    from protobuf_to_dict import protobuf_to_dict
  File "/usr/local/lib/python2.7/site-packages/protobuf_to_dict.py", line 7, in <module>
    from google.protobuf.descriptor import FieldDescriptor
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: libprotobuf.so.13: cannot open shared object file: No such file or directory

**Comment by walaoaaa1234** [comment]
# **Please note, deployments are not supported officially. You are using these deployment links at your own risk.**

**Comment by FrostTheFox** [comment]
^
