### ISSUE TITLE
Docker Pull no longer works as intended

### ISSUE THREAD

**Issue by Alphawarz** [RocketMap/RocketMap#2024]
Docker pull use to work flawlessly not too long ago (about 48 hours ago).

Now a brand new pull will cause:

Traceback (most recent call last):
  File "./runserver.py", line 20, in <module>
    from pogom.app import Pogom
  File "/usr/src/app/pogom/app.py", line 19, in <module>
    from .models import (Pokemon, Gym, Pokestop, ScannedLocation,
  File "/usr/src/app/pogom/models.py", line 36, in <module>
    from .account import (tutorial_pokestop_spin, get_player_level, check_login,
  File "/usr/src/app/pogom/account.py", line 10, in <module>
    from pgoapi import PGoApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 33, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/rpc_api.py", line 38, in <module>
    from protobuf_to_dict import protobuf_to_dict
  File "/usr/local/lib/python2.7/site-packages/protobuf_to_dict.py", line 7, in <module>
    from google.protobuf.descriptor import FieldDescriptor
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: libprotobuf.so.13: cannot open shared object file: No such file or directory

Which will automatically/immediately stop a docker container from running.
Perhaps this must be due to an update/change not configured in the dockerfile.

I would like to clarify i have been using docker with rocketmap for a while now (about three months or so), and never had this problem. I started from 0 to verify the problem was not on my end.

Hope this feedback helps.

**Comment by Alphawarz** [comment]
Thanks a lot, new rocketmap update has fixed the issue, latest pull seems to be working correctly for us Docker users.

Amazing job everyone.
