### ISSUE TITLE
Webhook Whitelist File parsing fails

### ISSUE THREAD

**Issue by neskk** [RocketMap/RocketMap#2039]
When using a file with Pokemon names for `webhook-whitelist-file` an exception occurs because get_pokemon_data() function in utils.py can't find the file `pokemon.min.json` (yes it exists, I double checked).

## Expected Behavior

webhook-whitelist-file: encounter.txt
## Current Behavior

```
Traceback (most recent call last):
  File "PokemonGo-Map/runserver.py", line 20, in <module>
    from pogom.app import Pogom
  File "D:\Workspace\Python\PokemonGo-Map\pogom\app.py", line 19, in <module>
    from .models import (Pokemon, Gym, Pokestop, ScannedLocation,
  File "D:\Workspace\Python\PokemonGo-Map\pogom\models.py", line 34, in <module>
    from .customLog import printPokemon
  File "D:\Workspace\Python\PokemonGo-Map\pogom\customLog.py", line 5, in <module>
    args = get_args()
  File "D:\Workspace\Python\PokemonGo-Map\pogom\utils.py", line 36, in wrapper
    rv = function(*args)
  File "D:\Workspace\Python\PokemonGo-Map\pogom\utils.py", line 697, in get_args
    f.read().splitlines()]
  File "D:\Workspace\Python\PokemonGo-Map\pogom\utils.py", line 807, in get_pokemo
    get_pokemon_data(1)
  File "D:\Workspace\Python\PokemonGo-Map\pogom\utils.py", line 798, in get_pokemo
    with open(file_path, 'r') as f:
IOError: [Errno 2] No such file or directory: 'static/dist/data\\pokemon.min.json'
```

## Possible Solution

utils.py L793
 ```
        file_path = os.path.join(
            config['ROOT_PATH'],
            config['DATA_DIR'],
            'pokemon.min.json')
```
Since `get_pokemon_data` function is being called before flask application is initialized `config['ROOT_PATH']` isn't defined.

```
        root_path = os.path.dirname(os.path.realpath(__file__)) + '/..'
        file_path = os.path.join(
            root_path,
            config['DATA_DIR'],
            'pokemon.min.json')
```
This seems to do the trick ;)

## Steps to Reproduce (for bugs)

1. Current version of develop branch.
2. File with Pokemon names, one by line.
3. pip install & npm install
4. Launch RocketMap with `--webhook-whitelist-file FILENAME_WITH_NAMES`

## Context

Setting webhook whitelist filter using a file.

## Your Environment

* Version used: Current develop branch
* Environment name and version (e.g. Python 2.7): 2.7.12
* Operating System and version (desktop or mobile): Win 7 x64

**Comment by sebastienvercammen** [comment]
Fixed with #2041.
