### ISSUE TITLE
Index column size too large

### ISSUE THREAD

**Issue by jangrewe** [RocketMap/RocketMap#2053]
## Expected Behavior
RocketMap starts, migrates the tables to the required schema, and everything's peachy.

## Current Behavior
RocketMap starts, migrates the tables to the required schema, but not quite...
```
2017-05-18 19:14:09,193 [        MainThread][        models][    INFO] Connecting to MySQL database on 172.17.0.1:3306...
2017-05-18 19:14:09,220 [        MainThread][        models][    INFO] Changing collation and charset on 15 tables.
2017-05-18 19:14:09,253 [        MainThread][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "./runserver.py", line 362, in <module>
    main()
  File "./runserver.py", line 231, in main
    verify_table_encoding(db)
  File "/usr/src/app/pogom/models.py", line 2689, in verify_table_encoding
    db.execute_sql(cmd_sql)
  File "/usr/local/lib/python2.7/site-packages/playhouse/shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 161, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/site-packages/pymysql/cursors.py", line 317, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1021, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/site-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/site-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1709, u'Index column size too large. The maximum column size is 767 bytes.')
```

**Comment by jangrewe** [comment]
Manually changing the collation for all tables to `utf8mb4_unicode_ci` fixes this.

**Comment by bbdoc** [comment]
@jangrewe Not correct, it will just throw the same error as your varchar(255) will still not fit. Changing all varchar(255) to varchar(191) does solve that but that's Something that should be handled by the migration procedure in the code.

**Comment by jangrewe** [comment]
@bbdoc Well, if that's not correct, then why does it work for me? I had a look at the code, and that's the step where it's failing, so it did it manually - and everything was fine.

**Comment by bbdoc** [comment]
It's working for you doesn't mean it's the good solution. Yes that's where it's failing, but doing it manually might not work better if the encoding change gets you over the limit. Code fails because varchar(255) is above limit, will still fail doing the same action manually, while changing it to varchar(191) and thus be under limits will solve it in all situations.

**Comment by sebastienvercammen** [comment]
While this issue happened because of some one-time DB schema updates around May which didn't handle existing columns with contents that were too long for the new type, I'm intentionally keeping this issue open because the issue will happen again in the future until DB migration is changed.
