### ISSUE TITLE
Unable to retrieve altitude from Google APIs: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by mermao1** [RocketMap/RocketMap#2091]
## Expected Behavior
RocketMap starts but can't connect to Google API.
Its a CERTIFICATE ERROR. (UNIX SYSTEM)

## Current Behavior
[root@local RocketMap]# python runserver.py -cf CENTRO.ini
2017-06-16 16:48:56,613 [        MainThread][      altitude][   ERROR] Unable to retrieve altitude from Google APIs: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579).
Traceback (most recent call last):
  File "/root/RocketMap/pogom/altitude.py", line 21, in get_gmaps_altitude
    timeout=5)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

## Solution
It is necessary to downgrade to an older version of certifi
root@localhost $ pip install certifi==2015.4.28

**Comment by kafeijao** [comment]
This also happened to me, and I use the same solution ^^
I run on CentOs 7 x64

**Comment by sebastienvercammen** [comment]
This workaround was added in the docs in #2115.
