### ISSUE TITLE
Cant start the Server

### ISSUE THREAD

**Issue by denniskai1234** [RocketMap/RocketMap#2256]
Hey guys,

i can start the server, no matter what config or options im using, i always get this:

2017-08-11 08:28:48,948 [        MainThread][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "./runserver.py", line 495, in <module>
    main()
  File "./runserver.py", line 199, in main
    if not regexp.match(args.status_name):
TypeError: expected string or buffer

**Comment by darkelement1987** [comment]
Config/command line? (leave hashkeys/google maps keys, personal info blank)

**Comment by sebastienvercammen** [comment]
Has already been fixed, `git pull` and restart.
