### ISSUE TITLE
Need to better handle flask 'broken pipe' errors

### ISSUE THREAD

**Issue by tomballgithub** [RocketMap/RocketMap#2277]
## Expected Behavior

Need to trap and cleanly handle the following issue.  It causes endless questions in #help and answer is always that it's a flask error that can be ignored.

```
2017-08-25 23:12:13,250 [     Thread-506835][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "runserver.py", line 89, in run
    run_old(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

## Current Behavior

The error above occurs

## Possible Solution

Trap this issue and only put a controlled error message in the log

## Steps to Reproduce (for bugs)

1. Run rocketmap for a while
2. Check logs
3. You likely will see this common error that can be ignored

## Context

Expectation is only to have real exceptions showing up in logs.  This is a known one.  If we address the issue and have a clean log entry it causes less headaches because when you look at the console and see an exception you will know it is something that merits investigation.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
Ubunto 16.04 VPS

**Comment by sebastienvercammen** [comment]
👍 As discussed on Discord, I'll take care of this asap.

**Comment by sebastienvercammen** [comment]
Updating Flask did resolve a related issue and handles requests better, but the exception still occurs. I'll submit another PR to handle that specific case.

**Comment by sebastienvercammen** [comment]
@tomballgithub Could you run #2304 (and approve if it works for you), then get it to log the "Broken pipe" exception details?

**Comment by tomballgithub** [comment]
`

2017-09-21 11:02:22,679 [         Thread-50][     runserver][CRITICAL] Unhandled patched exception (error): "".
2017-09-21 11:02:22,679 [         Thread-50][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "runserver.py", line 89, in run
    run_old(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

`

**Comment by tomballgithub** [comment]
I am getting hammered with these today.  Very annoying but easy to test for you

**Comment by tomballgithub** [comment]
@sebastienvercammen Seb, last night I upgraded to the current code base and I saw the following in the log just now.  I had previously been running the Aug31 code base with the flash broken pipe change implemented by PR without issue.

Note that this doesn't get put into the logs so there is no good way to search my logs for frequency of this.

```

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54096)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

```

**Comment by tomballgithub** [comment]
I saw the same thing on a 2nd server also:

```
----------------------------------------
Exception happened during processing of request from ('xx.yy.zz.aa', 52784)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

```

**Comment by nrupatunga** [comment]
any solution for the above. @tomballgithub , its been very annoying to deploy the app, which I need to continuously restart every time this happen. Did you find any solution ??

**Comment by tomballgithub** [comment]
Yes this issue was fixed but I am still seeing it rarely.  @seb gave me
something to try to fix it further but I have not yet had an opportunity.

It has never forced me to have to restart anything, it is just annoying.
