### ISSUE TITLE
IE problems displaying raids.  1st one shown, then no more.

### ISSUE THREAD

**Issue by dajoker17** [RocketMap/RocketMap#2289]
## Expected Behavior
Maps should show all raids as set by filters.

## Current Behavior
Using latest IE, load maps, turn on raids, and the first raid shows then no others.

console messages:
HTML1300: Navigation occurred.
192.168.1.162:5000
jQuery.Deferred exception: 'Notification' is undefined ReferenceError: 'Notification' is undefined
   at Anonymous function (http://192.168.1.162:5000/static/abcba52/dist/js/map.min.js:6:15352)
   at j (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29992)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313) undefined
SCRIPT5009: 'Notification' is undefined
jquery.min.js (2,31689)
SCRIPT438: Object doesn't support property or method 'repeat'
map.min.js (5,14239)

## Steps to Reproduce (for bugs)

Pull latest build.
Load IE 11.540.15063.0  Update versions 11.0.45
Load map.
(reset settings button at bottom if you like) - I have tried deleting cookies etc)
Turn off everything except raids
reload page.

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by BrownSlaughter** [comment]
IE11 support was dropped my Microsoft in January 2016. Please try a newer browser and see if the problem persists
