### ISSUE TITLE
Runserver.py got Errno 10013 An attemp was made to access a socket in a way forbidden...

### ISSUE THREAD

**Issue by hoang301** [RocketMap/RocketMap#2472]
After I followed all basic step that RocketMap distributed online everything sound like good and ready to run
with the command I tried (in RocketMap directory)
python runserver.py
then it showed below
Traceback (most recent call last):
File "runserver.py", line 568, in
main()
File "runserver.py", line 499, in main
host=args.host, port=args.port, ssl_context=ssl_context)
File "C:\Python27\lib\site-packages\flask\app.py", line 843, in run
run_simple(host, port, self, **options)
File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 694, in run_simple
inner()
File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 656, in inner
fd=fd)
File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 544, in make_server
passthrough_errors, ssl_context, fd=fd)
File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 464, in init
HTTPServer.init(self, (host, int(port)), handler)
File "C:\Python27\lib\SocketServer.py", line 417, in init
self.server_bind()
File "C:\Python27\lib\BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "C:\Python27\lib\SocketServer.py", line 431, in server_bind
self.socket.bind(self.server_address)
File "C:\Python27\lib\socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

I also tried to enable it in windows firewall (I running Windows 10 and IIS server)

Any suggestion would be helpful ...

Thank you

**Comment by FrostTheFox** [comment]
This is not an issue with RocketMap, this is an error caused by the Windows networking stack. Check if the appropriate rules have been created in Windows Firewall, try restarting Windows Firewall, try disabling Windows Firewall, try resetting your TCP/IP stack, if you're running any sort of Antivirus software, try disabling it, check that nothing else is using the port you're trying to run the webserver on. If you Google "An attempt was made to access a socket in a way forbidden by its access permissions", or better yet, "python An attempt was made to access a socket in a way forbidden by its access permissions", you'll get plenty of results with things you can try.

If you're still having issues, you may ask for further help in the RocketMap [Discord](https://discord.gg/rocketmap).

**Comment by hoang301** [comment]
Thank you for your time, I went over all your suggestions, I found the solution for this issue.
the port 5000 is not open in my router.
I first tried that I change another port that is available on my network such as 8000
and the command python runserver.py start to run but it handing in this part and repeat forever

2018-02-01 12:27:28,987 [   search-worker-0][       account][   ERROR] Login for account P0g02018 failed. Exception in call request: 400: Bad request, error: Key Expired!.
Traceback (most recent call last):
  File "D:\RocketMap\pogom\account.py", line 133, in rpc_login_sequence
    req.call(False)
  File "D:\RocketMap\pogom\pgorequestwrapper.py", line 55, in call
    return self.request.call(*args, **kwargs)
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 256, in call
    response = request.request(self._api_endpoint, self._req_method_list, self._req_platform_list, self.get_position(), use_dict)
  File "C:\Python27\lib\site-packages\pgoapi\rpc_api.py", line 132, in request
    self.request_proto = self.request_proto or self._build_main_request(subrequests, platforms, player_position)
  File "C:\Python27\lib\site-packages\pgoapi\rpc_api.py", line 215, in _build_main_request
    self._hash_engine.hash(sig.timestamp, request.latitude, request.longitude, request.accuracy, ticket_serialized, sig.session_hash, request.requests)
  File "C:\Python27\lib\site-packages\pgoapi\hash_server.py", line 50, in hash
    raise BadHashRequestException("400: Bad request, error: {}".format(response.text))
BadHashRequestException: 400: Bad request, error: Key Expired!
2018-02-01 12:27:29,096 [   search-worker-0][        search][   ERROR] Exception in search_worker under account P0g02018.
Traceback (most recent call last):
  File "D:\RocketMap\pogom\search.py", line 978, in search_worker_thread
    check_login(args, account, api, status['proxy_url'])
  File "D:\RocketMap\pogom\account.py", line 120, in check_login
    rpc_login_sequence(args, api, account)
  File "D:\RocketMap\pogom\account.py", line 144, in rpc_login_sequence
    account['username']))
LoginSequenceFail: Failed during empty request in login sequence for account P0g02018.
2018-02-01 12:27:39,157 [   search-worker-0][        search][    INFO] Waiting to get new account from the queue...
2018-02-01 12:28:18,437 [  account-recycler][        search][    INFO] Account recycler running. Checking status of 1 accounts.
2018-02-01 12:28:18,437 [  account-recycler][        search][    INFO] Account P0g02018 needs to cool off for 119.0 minutes due to exception.
2018-02-01 12:29:18,450 [  account-recycler][        search][    INFO] Account recycler running. Checking status of 1 accounts.

do you have any ideas how to fix it .... 
I can view RocketMap on my browser localhost:8000 but is showed the map only NO POKEMON or Stop or Gyms at all 
if you need to view please use http://ibi.ddns.net:8000 just FYI
Thanks

**Comment by hoang301** [comment]
I Think the problem maybe the hash key ... I though it free but not ... so I give up however thank you for you help and consideration.
