### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by run-dey** [RocketMap/RocketMap#2555]
I am using the latest build but I am getting this error
```
Map parse failed at 33.7416040,1.858872, abandoning location. myaccountname may be banned.. Exception message: ValueError('max() arg is an empty sequence',)
Traceback (most recent call last):
File "/home/pogom/pogom/search.py", line 1007, in search_worker_thread
scan_date, account, account_sets)
File "/home/pogom/pogom/models.py", line 2279, in parse_map
SpawnpointDetectionData.classify(sp, scan_loc, now_secs)
File "/home/pogom/pogom/models.py", line 1564, in classify
max_gap = max(gap_list)
ValueError: max() arg is an empty sequence
2018-13-07 01:35:32,532 [ search-worker-0][ search][ INFO] Map parse failed at 33.7416040,1.858872, abandoning location. myaccountname may be banned. Sleeping 2.819999s until 01:35:42.
```

What does this error relates to?

**Comment by FrostTheFox** [comment]
Automated mapping software isn't functional right now as no hashing service has been released for the latest game versions.
