### ISSUE TITLE
OperationalError: (1040, u'Too many connections') & TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by aldarund** [RocketMap/RocketMap#832]
After today update this error begin to popup right after workers start. Was working perfectly fine on yesterday commits, didnt changed a thing.
And now some workers begin to give first this errors like 5 times

```
2016-08-19 08:17:29,150 [      db-cleaner][        models][   ERROR] Exception in clean_db_loop: (1040, u'Too many connections')
Traceback (most recent call last):
  File "/opt/webapps/pogomap/PokemonGo-Map/pogom/models.py", line 555, in clean_db_loop
    query.execute()
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/peewee.py", line 3274, in execute
    return self.database.rows_affected(self._execute())
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/playhouse/shortcuts.py", line 207, in execute_sql
    cursor = self.get_cursor()
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/peewee.py", line 3431, in get_cursor
    return self.get_conn().cursor()
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/peewee.py", line 3424, in get_conn
    self.connect()
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/playhouse/pool.py", line 128, in _connect
    conn = super(PooledDatabase, self)._connect(*args, **kwargs)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/peewee.py", line 3929, in _connect
    return mysql.connect(db=database, **conn_kwargs)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/pymysql/connections.py", line 690, in __init__
    self.connect()
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/pymysql/connections.py", line 908, in connect
    self._request_authentication()
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/pymysql/connections.py", line 1116, in _request_authentication
    auth_packet = self._read_packet()
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/opt/webapps/pogomap/lib/python2.7/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
OperationalError: (1040, u'Too many connections')
```

And after it a bit different error 
TypeError: 'NoneType' object is not callable

```
Exception in thread db-cleaner:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/webapps/pogomap/PokemonGo-Map/pogom/models.py", line 567, in clean_db_loop
    log.exception('Exception in clean_db_loop: %s', e)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1193, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1186, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1278, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 1252, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/local/lib/python2.7/logging/__init__.py", line 269, in __init__
    if (args and len(args) == 1 and isinstance(args[0], collections.Mapping)
  File "/opt/webapps/pogomap/lib/python2.7/abc.py", line 144, in __instancecheck__
    return cls.__subclasscheck__(subtype)
  File "/opt/webapps/pogomap/lib/python2.7/abc.py", line 174, in __subclasscheck__
    for rcls in cls._abc_registry:
  File "/opt/webapps/pogomap/lib/python2.7/_weakrefset.py", line 59, in __iter__
    with _IterationGuard(self):
TypeError: 'NoneType' object is not callable
```

After second error the whole worker stop working and nothing happens in it, no new scan or log messages just nothing.

**Comment by pyr0ball** [comment]
What configuration are you using for database? Sqlite or mysql?

**Comment by aldarund** [comment]
On second restart it was just keeping spamming first error for 100mb + in logs . Something really not right with #582
@pyr0ball mysql

**Comment by pyr0ball** [comment]
Would you mind sharing your config? How many workers/accounts?

**Comment by aldarund** [comment]
@pyr0ball 50 separate python scan process. Each have 1-2 accounts.

**Comment by pyr0ball** [comment]
Try either editing my.cfg to allow more than 100 db connections, or run each worker instance ending with: --db-max-connections 500

**Comment by aldarund** [comment]
@pyr0ball well, its works perfectly fine with current config on any commit prior #582. Also it shouldnt in any case
1) crash log with TypeError: 'NoneType' object is not callable
2) spam log with 100mb+ of text within a minute

**Comment by pyr0ball** [comment]
True, just getting debug info for the backend dev's once they can take a look

**Comment by aldarund** [comment]
@chuyskywalker 
increasing max connections in mysql config fix the issue.
I guess that this commit increase number of connections with multiple python processes at least 2x. Thats probably because of db cleaner. I dont see why db cleaner should be run on every scan process, wouldnt it be better if there will be an option key to enable or disable it, so it wont be run on every python process?
Also problem with NoneType and 100mb+ spammed log when max connection reached are still remain a problem

**Comment by angrymoose** [comment]
@aldarund I would just disable the database cleaner using -pd 0 flag.

**Comment by aldarund** [comment]
@angrymoose i dont have -pd flag. its set to 0 by default, that db cleaner thread do something different, its not about pokemons data afaik.

**Comment by sharklab** [comment]
same here, @aldarund have you found a solution?

**Comment by aldarund** [comment]
@sharklab increase max_connection in mysql config. Additional connection caused by db cleaner thread that is run on every worker and no way to disable it as i see so far

**Comment by sharklab** [comment]
@aldarund the config key is "max-connections:" right?

**Comment by aldarund** [comment]
@sharklab https://mediatemple.net/community/products/dv/204404374/how-do-i-increase-the-mysql-connections-for-my-server

**Comment by Thyllz** [comment]
Run:
**show variables like "max_connections";**
(this shows the current limit)

Run:
**set global max_connections = 200;**
(where 200 = whatever # you want to increase the limit to)

Hope this helps.

**Comment by sebastienvercammen** [comment]
Issue is no longer related to the current codebase (and not a code problem: if your setup needs additional connections, you need to edit your MySQL config), so we're closing the issue.
