### ISSUE TITLE
Failed ptc auth tokens are not handled correctly -> TypeError: sequence index must be integer, not 'str'

### ISSUE THREAD

**Issue by aldarund** [RocketMap/RocketMap#920]
When a ptc token failed to get with following error

`2016-08-22 09:12:42,947 [     ss-worker-0][      auth_ptc][   ERROR] Could not retrieve token! ('errors')`
Search still trying to load map_cells and fails with TypeError: sequence index must be integer, not 'str'

```
2016-08-22 09:12:42,959 [     ss-worker-0][        search][   ERROR] Exception in search_worker: sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "/opt/webapps/pogomap/PokemonGo-Map/pogom/search.py", line 609, in search_worker_thread_ss
    findCount = parse_map(args, response_dict, step_location, dbq, whq)
  File "/opt/webapps/pogomap/PokemonGo-Map/pogom/models.py", line 383, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
TypeError: sequence index must be integer, not 'str'
```

**Comment by aldarund** [comment]
Another example with a bit different initial error message

```
2016-08-22 11:18:18,278 [     ss-worker-0][      auth_ptc][   ERROR] PTC User Login Error - Field missing in response: No JSON object could be decoded
2016-08-22 11:18:18,290 [     ss-worker-0][        search][   ERROR] Exception in search_worker: sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "/opt/webapps/pogomap/PokemonGo-Map/pogom/search.py", line 609, in search_worker_thread_ss
    findCount = parse_map(args, response_dict, step_location, dbq, whq)
  File "/opt/webapps/pogomap/PokemonGo-Map/pogom/models.py", line 383, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
TypeError: sequence index must be integer, not 'str'
```
Accounts not banned, after few retries they begin to work. A problem is just with handling such invalid login responses

**Comment by amistad18** [comment]
I had the same issue today for 7 out of 10 accounts. First `TC User Login Error - Field missing in response: No JSON object could be decoded`, then `Exception in search_worker: sequence index must be integer, not 'str'` until I restarted them manually, and the login actually passes.

**Comment by matpag** [comment]
For me it's not working, some auto-generated PTC accounts report : 
Could not retrieve token: Account is not yet active, please redirect.

While some other are reporting: 
2016-08-22 19:57:23,354 [ search_worker_2][        search][   ERROR] Exception in search_worker: sequence index must be integer, not 'str'. Username: nichfrofh

**Comment by aldarund** [comment]
@matpag its totally different and unrelated. Ur accounts just not email verified.

**Comment by amistad18** [comment]
@matpag check this out - https://github.com/TachyonRSA/PoGoTos

**Comment by silentj94** [comment]
@amistad18 where do you put that file and how do you run it?

**Comment by voignar** [comment]
You must enter the game with bills to name selection. Once willow finishes speaking, you can now use that account

**Comment by aldarund** [comment]
@silentj94 @voignar thats really not a place for such discussions. Go to discord or help forums guys

**Comment by silentj94** [comment]
@aldarund sorry will do, thanks

**Comment by silentj94** [comment]
@aldarund i get the following error message, is this the same issue?

2016-08-23 11:32:03,294 [ search-worker-0][        search][   ERROR] Map parse failed at 52.651527,-1.050683, abandoning location. silentj94 may be banned.
Traceback (most recent call last):
  File "/Users/jasat/Desktop/PokemonGo/PokemonGo-Map/pogom/search.py", line 510, in search_worker_thread
    findCount = parse_map(args, response_dict, step_location, dbq, whq)
  File "/Users/jasat/Desktop/PokemonGo/PokemonGo-Map/pogom/models.py", line 387, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

**Comment by voignar** [comment]
@aldarund I had the same error and I said as I settled. But if you want my solution, do not worry that you will not say anything more. You do well in discord

**Comment by aldarund** [comment]
@silentj94 no its not. ur account banned or no ingame tos accepted

**Comment by sebastienvercammen** [comment]
Issue is no longer related to the current codebase, so we're closing the issue. If anyone still has the problem, please post additional data on latest commit and we'll reopen.
